apiVersion: v1
kind: Service
metadata:
  name: hello-js-k8s-service
  namespace: default-1657428683215
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      name: port80
      port: 80
      protocol: TCP
    - targetPort: 3000
      name: port3000
      port: 3000
      protocol: TCP
  selector:
    app: hello-js-k8s
